Uses of NumPy
1. Arithmetic operations
2. Statistical operations
3. Bitwise operators
4. Copying and viewing arrays
5. Stacking
6. Matrix operations
7. Linear Algebra
8. broadcasting
9. Mathematical Operations
10. Searching, sorting and counting

1. Array Creation Function

In [1]:
import numpy as np

In [4]:
#creat an array from a list
a= np.array([1,2,3])
print('Array a:', a)

Array a: [1 2 3]


In [6]:
#creat an array with evenly spaced values
b= np.arange(0,10,2) #values from 0 to 10 with step 2
print('Array b:', b)

Array b: [0 2 4 6 8]


In [8]:
#Creat an array with linearly spaced values
c= np.linspace(0,1,5)
print('Array c:', c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [10]:
#Creat an array filled with zeros
d= np.zeros((2,3))
print('Array d:\n', d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#creat an array filled with ones
e= np.ones((3,2))
print('Array e:\n', e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
#creat an identity matrix
f= np.eye(4) #4x4 identity matrix
print('identity matrix f:\n', f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Array Manipulation Functions

In [21]:
#Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3))
print('Reshaped array:', reshaped)

Reshaped array: [[1 2 3]]


In [23]:
#Flatten an array
f1= np.array([[1,2],[3,4]])
flattened = np.ravel(f1) 
print('Flattened array:', flattened)

Flattened array: [1 2 3 4]


In [25]:
#Transpose an array
e1= np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print('Transposed array:\n', transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [27]:
#Stack arrays vertically
a2 = np.array([1,2])
b2= np.array([3,4])
stacked = np.vstack([a2,b2]) #vertical staking
print('Vertical stacked arrays:\n', stacked)

Vertical stacked arrays:
 [[1 2]
 [3 4]]


In [29]:
stacked1= np.hstack([a2,b2]) #horizontal stacked
print('Horizontal stacked arrays:\n', stacked1)

Horizontal stacked arrays:
 [1 2 3 4]


In [43]:
#Splitting an array
a3= np.arange(0,12).reshape(3,4)
split= np.hsplit(a3,2) #horizontal splitting
print('Horizontal splitted arrays:\n', split)

Horizontal splitted arrays:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [49]:
split1= np.vsplit(a3,3)
print('Vertical splitted arrays:\n', split1)

Vertical splitted arrays:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


3. Mathematical Function

In [54]:
#Add two arrays
g= np.array([1,2,3,4])
added= np.add(g,2) #add 2 to each element
print('Added 2 to g:', added)

Added 2 to g: [3 4 5 6]


In [56]:
#Square each element
squared= np.power(g,2) #square each element
print('Squared g:', squared)

Squared g: [ 1  4  9 16]


In [58]:
#Square root of each element
sqrt_val = np.sqrt(g) #square root of each element
print('Square root of g:', sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [68]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [76]:
# Dot product of two arrays
dot_product= np.dot(a1, g) #error is because of matrix size is not same
print('Dot product of a and g:', dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [66]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [72]:
dot_product= np.dot(a1,a)
print('Dot product of a1 and a:\n', dot_product )

Dot product of a1 and a:
 14


4. Statistical Functions

In [79]:
s= np.array([1,2,3,4])
mean= np.mean(s)
print('Mean of s:', mean)

Mean of s: 2.5


In [81]:
#Standard deviation of an array
std_dev= np.std(s)
print('Standard deviation of s:', std_dev)

Standard deviation of s: 1.118033988749895


In [83]:
#Minimum element of an array
minimum = np.min(s)
print('Minimum of s:', minimum)

Minimum of s: 1


In [85]:
#Maximum element of an array
maximum= np.max(s)
print('Maximum of s:', maximum)

Maximum of s: 4


5. Linear Algebra Function

In [3]:
#Creat a matrix
matrix = np.array([[1,2],[3,4]])

In [5]:
#Determinant of a matrix
determinant = np.linalg.det(matrix)
print('Determinant of matrix:', determinant)

Determinant of matrix: -2.0000000000000004


In [7]:
#Inverse of a matrix
inverse = np.linalg.inv(matrix)
print('Inverse of matrix;\n', inverse)

Inverse of matrix;
 [[-2.   1. ]
 [ 1.5 -0.5]]


6. Random Sampling Functions

In [10]:
#Generate random values between 0 and 1
random_vals = np.random.rand(3) #array of 3 random values between 0 and 1
print('Random values:', random_vals)

Random values: [0.45401905 0.3849265  0.37843309]


In [14]:
# Set seed for reproducibility
np.random.seed(0)
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [16]:
 # Generate random integers
rand_int = np.random.randint(0,10,size=5)
print('Random intergers:', rand_int)

Random intergers: [3 7 9 3 5]


In [18]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


7. Boolean and Logical Functions

In [21]:
# Check if all the elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) #check if all are true
print('All elements True:', all_true)

All elements True: False


In [23]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [27]:
# Check if any elements are True
# any
logical_test = np.array([True, False, True])
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


8. Set Operations

In [30]:
# Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a, set_b)
print('Intersection of a and b:', intersection)

Intersection of a and b: [3 4]


In [32]:
# Union of two arrays
union= np.union1d(set_a, set_b)
print('Union of a and b:',union )

Union of a and b: [1 2 3 4 5 6]


In [36]:
set_a = np.arange(6).reshape(2,3)
set_b = np.arange(6,12).reshape(2,3)
union= np.union1d(set_a, set_b)
print('Union of a and b:', union)

Union of a and b: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
set_a = np.arange(6).reshape(2,3)
set_b = np.arange(4,10).reshape(2,3)
intersection = np.intersect1d(set_a, set_b)
print('intersection of a and b:', intersection)

intersection of a and b: [4 5]


9. Array Attribute Functions

In [41]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


10. Other Functions

In [44]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a) 
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [46]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [48]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
